In [1]:
from tranction_reduction import TranctionReduction
import pandas as pd
import numpy as np
import numpy_indexed as npi
from itertools import combinations, product
from functools import reduce
from collections.abc import Iterable
import math
import timeit
# use for vertify
import matplotlib.pyplot as plt
from apriori import apriori

In [2]:
real_dataset_path = "/home/sokhorn/sokhorn/dataSet/data/Online Retail.csv"
# testing_dataset_path = '/home/sokhorn/sokhorn/dataSet/data/sample_data_set.csv'
tranction_reduction_itemsets = '/home/sokhorn/sokhorn/dataSet/data/sample_tranc_red.csv'
sample_dataset = pd.read_csv(
    tranction_reduction_itemsets, sep=',', usecols=[
        'InvoiceNo',
        'StockCode',
        'Quantity'
    ])
sample_dataset
item_sets = (
    sample_dataset.groupby(['InvoiceNo', 'StockCode', ])['Quantity']
    .sum().unstack().reset_index().fillna(0)
    .set_index("InvoiceNo")
)
# item_sets = item_sets.iloc[:, :150] 
# item_sets = item_sets.head(958)
item_sets = item_sets.applymap(lambda x: 1 if x > 0 else 0)
item_sets.reindex(sorted(item_sets.columns), axis=1)
item_sets

StockCode  I1  I2  I3  I4  I5
InvoiceNo                    
1           1   1   0   0   1
2           0   1   0   1   0
3           0   1   1   0   0
4           1   1   0   1   0
5           1   0   1   0   0
6           0   1   1   0   0
7           1   0   1   0   0
8           1   1   1   0   1
9           1   1   1   0   0

In [3]:
apriori(item_sets)

X : [[1 1 0 0 1]
 [0 1 0 1 0]
 [0 1 1 0 0]
 [1 1 0 1 0]
 [1 0 1 0 0]
 [0 1 1 0 0]
 [1 0 1 0 0]
 [1 1 1 0 1]
 [1 1 1 0 0]]
X : 9

---------

Itemset [[1 1 0 0 1]
 [0 1 0 1 0]
 [0 1 1 0 0]
 [1 1 0 1 0]
 [1 0 1 0 0]
 [0 1 1 0 0]
 [1 0 1 0 0]
 [1 1 1 0 1]
 [1 1 1 0 0]] : support : [0.66666667 0.77777778 0.66666667 0.22222222 0.22222222]

---------

itemset_dict : [[0]
 [1]
 [2]]
X : [[ True False False]
 [False False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False False  True]
 [False  True False]
 [ True  True  True]
 [ True  True  True]]
X : 9.0


support itemsets
0  0.666667      (0)
1  0.777778      (1)
2  0.666667      (2)