In [5]:
import numpy as np

In [6]:
X = np.array([
    [1, 1, 1, 0],
    [0, 1, 1, 1],
    [1, 0, 1, 1],
    [1, 1, 0, 0],
])

In [7]:
itemset_rc = np.array([[1, 1, 1, 1],
                       [1, 0, 1, 1],
                       [1, 1, 0, 0],
                       [1, 1, 1, 0]])
RC = np.array([1, 1, 1, 1])


In [8]:
from functools import reduce
min_support = 0.5


def _support(_x, _n_rows,):
    out = (np.sum(_x, axis=0) / _n_rows)
    tranc_support = support_k_itemst(_x)
    print(tranc_support)
    return np.array(out).reshape(-1)


# reduce(function, input)
def support_k_itemst(k_itemst):
    s = 0
    for i in range(len(k_itemst)):
        s += reduce(lambda a, b: a & b, k_itemst[i] & RC[i])
    return s


In [9]:
support = _support(X, 4)
ary_col_idx = np.arange(X.shape[1])
support_dict = {1: support[support >= min_support]}
itemset_dict = {1: ary_col_idx[support >= min_support].reshape(-1, 1)}
support

0


array([0.75, 0.75, 0.75, 0.5 ])

In [10]:
def generate_new_combinations(old_combinations):
    items_types_in_previous_step = np.unique(old_combinations.flatten())
    for old_combination in old_combinations:
        max_combination = old_combination[-1]  # get a single item in the last
        mask = items_types_in_previous_step > max_combination
        valid_items = items_types_in_previous_step[mask]
        old_tuple = tuple(old_combination)
        for item in valid_items:
            yield from old_tuple
            yield item


In [11]:
row_count = float(X.shape[0])
combin = generate_new_combinations(itemset_dict[1])
combin = np.fromiter(combin, dtype=int)
combin = combin.reshape(-1, 2)
combin

array([[0, 1],
       [0, 2],
       [0, 3],
       [1, 2],
       [1, 3],
       [2, 3]])

In [12]:
X[:, combin]

array([[[1, 1],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 0]],

       [[0, 1],
        [0, 1],
        [0, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 0],
        [1, 1],
        [1, 1],
        [0, 1],
        [0, 1],
        [1, 1]],

       [[1, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 0]]])

In [13]:
item = np.array([[True,  True, True,  True, True, True],
                 [True,  True, True,  True, True, True],
                 [True,  True, True,  True, True, True],
                 [True,  True, True,  True, True, False]])
support_k_itemst(item)
# TODO : to be continue here


3

In [14]:
# compare every row 
_bools = np.all(X[:, combin],axis=2)
_bools

array([[ True,  True, False,  True, False, False],
       [False, False, False,  True,  True,  True],
       [False,  True,  True, False, False,  True],
       [ True, False, False, False, False, False]])

In [15]:
support = _support(_bools, row_count)
_mask =  (support >= min_support).reshape(-1)
freq_2_itemset = np.array(combin[_mask]) 
support_2_itemset =  np.array(support[_mask])
freq_2_itemset

0


array([[0, 1],
       [0, 2],
       [1, 2],
       [2, 3]])

In [18]:
x = np.array([
    [0, 1, 0, 1, 0],
    [0, 1, 1, 0, 0],
    [1, 0, 1, 0, 0],
    [1, 1, 0, 0, 1],
    [1, 1, 0, 1, 0],
    [1, 1, 1, 0, 0],
    [1, 1, 1, 0, 1], ])

combine = np.array([[5, 6],
                    [4, 5],
                    [4, 6],
                    [2, 4],
                    [2, 5],
                    [2, 6],
                    [2, 4],
                    [2, 5],
                    [2, 6], ])


In [20]:
combine = np.array([[5, 6],
                    [4, 5],
                    [4, 6],
                    [2, 4],
                    [2, 5],
                    [2, 6],
                    [2, 4],
                    [2, 5],
                    [2, 6], ])
                    
np.all(x[:, combin], axis=2)


array([[False, False, False, False,  True, False],
       [False, False, False,  True, False, False],
       [False,  True, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False,  True, False,  True, False],
       [ True,  True, False,  True, False, False],
       [ True,  True, False,  True, False, False]])

In [28]:
ab = np.array([
    [0, 1, 0, 1, 0],
    [0, 1, 1, 0, 0],
    [1, 0, 1, 0, 0],
    [1, 1, 0, 0, 1],
    [1, 1, 0, 1, 0],
    [1, 1, 1, 0, 0],
    [1, 1, 1, 0, 1], ])
combine = np.array([
    [5, 6],
    [4, 5],
    [4, 6],
    [2, 4],
    [2, 5],
    [2, 6],
    [2, 4],
    [2, 5],
    [2, 6], ])
np.all(ab[:, combin], axis=2)


array([[False, False, False, False,  True, False],
       [False, False, False,  True, False, False],
       [False,  True, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False,  True, False,  True, False],
       [ True,  True, False,  True, False, False],
       [ True,  True, False,  True, False, False]])

In [1]:
a = [
    [
        [0, 1],
        [0, 0],
        [0, 1],
        [0, 0],
        [1, 0],
        [1, 1],
        [1, 0],
        [0, 1],
        [0, 0],
        [1, 0]
    ],
    [
        [0, 1],
        [0, 1],
        [0, 0],
        [0, 0],
        [1, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 0]
    ],
]
